#![no_std]
#![no_main]

extern crate alloc;

use esp_backtrace as _;
use esp_hal::{
    delay::Delay,
    gpio::{Input, InputConfig, Pull},
    main,
    time::Instant,
};
use esp_println::println;

use embedded_graphics::{
    image::{Image, ImageRaw},
    mono_font::{
        ascii::{
            FONT_10X20, FONT_4X6, FONT_5X7, FONT_6X9, FONT_7X13, FONT_7X13_BOLD, FONT_7X13_ITALIC,
            FONT_9X18, FONT_9X18_BOLD,
        },
        MonoTextStyle, MonoTextStyleBuilder,
    },
    pixelcolor::{raw::BigEndian, Gray4},
    prelude::*,
    primitives::{Circle, Line, PrimitiveStyle, Rectangle},
    text::{Alignment, Text},
};

use epaper::driver::{Display, DrawMode};

esp_bootloader_esp_idf::esp_app_desc!();

// ── Synthetic image assets (generated by build.rs) ───────────────────────────

// 960×270 four-quadrant test card: gradient / checkerboard / bands / Chebyshev rings
static CARD_DATA: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/card.bin"));

// 960×50 smooth horizontal gradient strip (used on grayscale screen)
static STRIP_DATA: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/strip.bin"));

// ── String buffer for on-screen number formatting ────────────────────────────

struct Buf<const N: usize> {
    data: [u8; N],
    len: usize,
}

impl<const N: usize> Buf<N> {
    fn new() -> Self {
        Self {
            data: [0u8; N],
            len: 0,
        }
    }

    fn push_str(&mut self, s: &str) {
        for b in s.bytes() {
            if self.len < N {
                self.data[self.len] = b;
                self.len += 1;
            }
        }
    }

    fn push_u64(&mut self, mut n: u64) {
        if n == 0 {
            self.push_str("0");
            return;
        }
        let mut tmp = [0u8; 20];
        let mut i = 20usize;
        while n > 0 && i > 0 {
            i -= 1;
            tmp[i] = b'0' + (n % 10) as u8;
            n /= 10;
        }
        self.push_str(core::str::from_utf8(&tmp[i..]).unwrap_or("?"));
    }

    fn as_str(&self) -> &str {
        core::str::from_utf8(&self.data[..self.len]).unwrap_or("")
    }
}

// ── Shared helpers ────────────────────────────────────────────────────────────

fn wait_for_button(button: &Input, delay: &Delay) {
    while button.is_high() {}
    delay.delay_millis(50);
    while button.is_low() {}
    delay.delay_millis(50);
}

// ── Screen 0: Title ───────────────────────────────────────────────────────────

fn draw_title(display: &mut Display) {
    let large = MonoTextStyle::new(&FONT_10X20, Gray4::BLACK);
    let small = MonoTextStyle::new(&FONT_7X13, Gray4::BLACK);

    Rectangle::new(Point::new(16, 16), Size::new(928, 508))
        .into_styled(PrimitiveStyle::with_stroke(Gray4::BLACK, 2))
        .draw(display)
        .unwrap();

    Text::with_alignment(
        "Graphics Test",
        Point::new(480, 80),
        large,
        Alignment::Center,
    )
    .draw(display)
    .unwrap();

    Line::new(Point::new(80, 100), Point::new(880, 100))
        .into_styled(PrimitiveStyle::with_stroke(Gray4::BLACK, 1))
        .draw(display)
        .unwrap();

    Text::with_alignment(
        "Lilygo T5 E-Paper S3 Pro  |  960x540  |  16 grey  |  ESP32-S3 @ 240 MHz",
        Point::new(480, 135),
        small,
        Alignment::Center,
    )
    .draw(display)
    .unwrap();

    let items = [
        "1. Shapes — lines, circles, rectangles, triangle",
        "2. Typography — 9 fonts, bold, italic, underline, strikethrough, alignment",
        "3. Grayscale — all 16 levels + smooth gradient via ImageRaw",
        "4. Image — 960x270 test card: gradient, checkerboard, bands, rings",
        "5. Animation — partial refresh timing (tainted-row optimisation)",
        "6. Timing summary — full vs partial flush measured in ms",
    ];
    for (i, item) in items.iter().enumerate() {
        Text::new(item, Point::new(80, 200 + i as i32 * 40), small)
            .draw(display)
            .unwrap();
    }

    Text::with_alignment(
        "Press BOOT (GPIO 0) to advance through each screen.",
        Point::new(480, 510),
        small,
        Alignment::Center,
    )
    .draw(display)
    .unwrap();
}

// ── Screen 1: Shapes ──────────────────────────────────────────────────────────

fn draw_shapes(display: &mut Display) {
    let s1 = PrimitiveStyle::with_stroke(Gray4::BLACK, 1);
    let s2 = PrimitiveStyle::with_stroke(Gray4::BLACK, 2);
    let s4 = PrimitiveStyle::with_stroke(Gray4::BLACK, 4);
    let s8 = PrimitiveStyle::with_stroke(Gray4::BLACK, 8);
    let filled = PrimitiveStyle::with_fill(Gray4::BLACK);
    let label = MonoTextStyle::new(&FONT_6X9, Gray4::BLACK);

    // Section labels
    Text::new("Lines (8 directions)", Point::new(10, 16), label)
        .draw(display)
        .unwrap();
    Text::new("Circles (filled & stroked)", Point::new(340, 16), label)
        .draw(display)
        .unwrap();
    Text::new("Stroke widths", Point::new(10, 296), label)
        .draw(display)
        .unwrap();
    Text::new("Triangle", Point::new(340, 296), label)
        .draw(display)
        .unwrap();
    Text::new("Grey levels", Point::new(660, 296), label)
        .draw(display)
        .unwrap();

    // Dividers
    Line::new(Point::new(320, 0), Point::new(320, 540))
        .into_styled(s1)
        .draw(display)
        .unwrap();
    Line::new(Point::new(640, 270), Point::new(640, 540))
        .into_styled(s1)
        .draw(display)
        .unwrap();
    Line::new(Point::new(0, 270), Point::new(960, 270))
        .into_styled(s1)
        .draw(display)
        .unwrap();

    // ── Lines radiating from (155, 155) ──────────────────────────────────────
    let cx = 155i32;
    let cy = 155i32;
    // (dx, dy) at 45° increments, length ≈ 120 (diagonal = 120*0.707 ≈ 85)
    let dirs: [(i32, i32); 8] = [
        (120, 0),
        (85, 85),
        (0, 120),
        (-85, 85),
        (-120, 0),
        (-85, -85),
        (0, -120),
        (85, -85),
    ];
    for (dx, dy) in dirs {
        Line::new(Point::new(cx, cy), Point::new(cx + dx, cy + dy))
            .into_styled(s2)
            .draw(display)
            .unwrap();
    }
    // Centre dot
    Circle::new(Point::new(cx - 4, cy - 4), 8)
        .into_styled(filled)
        .draw(display)
        .unwrap();

    // ── Concentric circles at (480 + 160, 135) = (640-160+160...) ────────────
    // Right of divider at x=320, centre around (490, 140)
    let cc_x = 490i32;
    let cc_y = 140i32;
    let radii: [u32; 5] = [20, 45, 70, 95, 120];
    for (i, r) in radii.iter().enumerate() {
        let r = *r;
        let style = if i % 2 == 0 { filled } else { s2 };
        Circle::new(Point::new(cc_x - r as i32, cc_y - r as i32), r * 2)
            .into_styled(style)
            .draw(display)
            .unwrap();
    }

    // ── Stroke-width rectangles (bottom-left) ─────────────────────────────────
    let styles = [s1, s2, s4, s8];
    let labels = ["1 px", "2 px", "4 px", "8 px"];
    for (i, (st, lbl)) in styles.iter().zip(labels.iter()).enumerate() {
        let y = 300 + i as i32 * 55;
        Rectangle::new(Point::new(50, y), Size::new(240, 40))
            .into_styled(*st)
            .draw(display)
            .unwrap();
        Text::new(lbl, Point::new(55, y + 26), label)
            .draw(display)
            .unwrap();
    }

    // ── Triangle (bottom-centre) ──────────────────────────────────────────────
    // Workaround: embedded-graphics 0.8.2 overflows i32 in ClosedThickSegmentIter
    // for large coordinates with any stroke width. Draw as 3 separate lines instead.
    let tri_a = Point::new(480, 310);
    let tri_b = Point::new(360, 520);
    let tri_c = Point::new(600, 520);
    Line::new(tri_a, tri_b)
        .into_styled(s4)
        .draw(display)
        .unwrap();
    Line::new(tri_b, tri_c)
        .into_styled(s4)
        .draw(display)
        .unwrap();
    Line::new(tri_c, tri_a)
        .into_styled(s4)
        .draw(display)
        .unwrap();

    // ── Grey-level horizontal lines (bottom-right) ────────────────────────────
    let grey_levels: [u8; 8] = [0, 2, 4, 6, 8, 10, 12, 14];
    for (i, luma) in grey_levels.iter().enumerate() {
        let y = 305 + i as i32 * 27;
        let color = Gray4::new(*luma);
        let gs = PrimitiveStyle::with_stroke(color, 4);
        Line::new(Point::new(660, y), Point::new(940, y))
            .into_styled(gs)
            .draw(display)
            .unwrap();
        let mut buf = Buf::<8>::new();
        buf.push_str("0x");
        buf.push_u64(*luma as u64);
        Text::new(buf.as_str(), Point::new(900, y - 2), label)
            .draw(display)
            .unwrap();
    }
}

// ── Screen 2: Typography ──────────────────────────────────────────────────────

fn draw_typography(display: &mut Display) {
    let heading = MonoTextStyle::new(&FONT_10X20, Gray4::BLACK);
    Text::new("Typography", Point::new(40, 30), heading)
        .draw(display)
        .unwrap();
    Line::new(Point::new(40, 40), Point::new(920, 40))
        .into_styled(PrimitiveStyle::with_stroke(Gray4::BLACK, 1))
        .draw(display)
        .unwrap();

    macro_rules! font_line {
        ($font:expr, $desc:expr, $y:expr, $display:expr) => {
            Text::new(
                concat!($desc, " — The quick brown fox (0123456789)"),
                Point::new(40, $y),
                MonoTextStyle::new(&$font, Gray4::BLACK),
            )
            .draw($display)
            .unwrap();
        };
    }

    font_line!(FONT_4X6, "FONT_4X6        ", 65, display);
    font_line!(FONT_5X7, "FONT_5X7        ", 82, display);
    font_line!(FONT_6X9, "FONT_6X9        ", 102, display);
    font_line!(FONT_7X13, "FONT_7X13       ", 124, display);
    font_line!(FONT_7X13_BOLD, "FONT_7X13_BOLD  ", 148, display);
    font_line!(FONT_7X13_ITALIC, "FONT_7X13_ITALIC", 172, display);
    font_line!(FONT_9X18, "FONT_9X18       ", 200, display);
    font_line!(FONT_9X18_BOLD, "FONT_9X18_BOLD  ", 230, display);
    font_line!(FONT_10X20, "FONT_10X20      ", 262, display);

    // Decorations
    Line::new(Point::new(40, 295), Point::new(920, 295))
        .into_styled(PrimitiveStyle::with_stroke(Gray4::BLACK, 1))
        .draw(display)
        .unwrap();
    Text::new(
        "Decorations:",
        Point::new(40, 310),
        MonoTextStyle::new(&FONT_7X13, Gray4::BLACK),
    )
    .draw(display)
    .unwrap();

    let underline_style = MonoTextStyleBuilder::new()
        .font(&FONT_9X18)
        .text_color(Gray4::BLACK)
        .underline_with_color(Gray4::BLACK)
        .build();
    Text::new("Underlined text", Point::new(40, 340), underline_style)
        .draw(display)
        .unwrap();

    let strike_style = MonoTextStyleBuilder::new()
        .font(&FONT_9X18)
        .text_color(Gray4::BLACK)
        .strikethrough_with_color(Gray4::BLACK)
        .build();
    Text::new("Strikethrough text", Point::new(40, 375), strike_style)
        .draw(display)
        .unwrap();

    // Alignment demo
    Line::new(Point::new(40, 415), Point::new(920, 415))
        .into_styled(PrimitiveStyle::with_stroke(Gray4::BLACK, 1))
        .draw(display)
        .unwrap();
    Text::new(
        "Alignment:",
        Point::new(40, 430),
        MonoTextStyle::new(&FONT_7X13, Gray4::BLACK),
    )
    .draw(display)
    .unwrap();
    let align_style = MonoTextStyle::new(&FONT_9X18, Gray4::BLACK);
    Text::with_alignment(
        "Left-aligned",
        Point::new(40, 470),
        align_style,
        Alignment::Left,
    )
    .draw(display)
    .unwrap();
    Text::with_alignment(
        "Centered",
        Point::new(480, 470),
        align_style,
        Alignment::Center,
    )
    .draw(display)
    .unwrap();
    Text::with_alignment(
        "Right-aligned",
        Point::new(920, 470),
        align_style,
        Alignment::Right,
    )
    .draw(display)
    .unwrap();

    // Vertical guide line for alignment
    Line::new(Point::new(480, 455), Point::new(480, 490))
        .into_styled(PrimitiveStyle::with_stroke(Gray4::new(8), 1))
        .draw(display)
        .unwrap();
}

// ── Screen 3: Grayscale ───────────────────────────────────────────────────────

fn draw_grayscale(display: &mut Display) {
    let heading = MonoTextStyle::new(&FONT_10X20, Gray4::BLACK);
    let label = MonoTextStyle::new(&FONT_7X13, Gray4::BLACK);

    Text::new("Grayscale — 16 levels", Point::new(40, 30), heading)
        .draw(display)
        .unwrap();
    Line::new(Point::new(40, 42), Point::new(920, 42))
        .into_styled(PrimitiveStyle::with_stroke(Gray4::BLACK, 1))
        .draw(display)
        .unwrap();

    // 16 bars, each 25 px tall + 1 px gap, from black (0) to white (15)
    for luma in 0u8..16 {
        let y = 55 + luma as i32 * 26;
        let color = Gray4::new(luma);

        Rectangle::new(Point::new(120, y), Size::new(760, 22))
            .into_styled(PrimitiveStyle::with_fill(color))
            .draw(display)
            .unwrap();

        // Outline so white bars are visible
        Rectangle::new(Point::new(120, y), Size::new(760, 22))
            .into_styled(PrimitiveStyle::with_stroke(Gray4::new(8), 1))
            .draw(display)
            .unwrap();

        // Label on the left
        let mut buf = Buf::<8>::new();
        buf.push_str("0x");
        buf.push_u64(luma as u64);
        Text::new(buf.as_str(), Point::new(60, y + 16), label)
            .draw(display)
            .unwrap();

        // Label on the right
        let luma_label = match luma {
            0 => "black",
            15 => "white",
            _ => "",
        };
        if !luma_label.is_empty() {
            Text::new(luma_label, Point::new(890, y + 16), label)
                .draw(display)
                .unwrap();
        }
    }

    // Gradient strip below bars via ImageRaw
    Text::new(
        "ImageRaw<Gray4> smooth gradient (960 x 50):",
        Point::new(40, 478),
        label,
    )
    .draw(display)
    .unwrap();

    let raw = ImageRaw::<Gray4, BigEndian>::new(STRIP_DATA, 960);
    Image::new(&raw, Point::new(0, 490)).draw(display).unwrap();
}

// ── Screen 4: Image test card ─────────────────────────────────────────────────

fn draw_image(display: &mut Display) {
    let heading = MonoTextStyle::new(&FONT_10X20, Gray4::BLACK);
    let label = MonoTextStyle::new(&FONT_6X9, Gray4::BLACK);

    Text::new(
        "ImageRaw<Gray4> — 960x270 test card",
        Point::new(40, 22),
        heading,
    )
    .draw(display)
    .unwrap();

    // Draw the 960×270 card centred vertically (y=135 puts it in rows 135-404)
    let raw = ImageRaw::<Gray4, BigEndian>::new(CARD_DATA, 960);
    Image::new(&raw, Point::new(0, 135)).draw(display).unwrap();

    // Quadrant labels (drawn on top of image — use mid-gray for visibility)
    let mid = MonoTextStyle::new(&FONT_7X13, Gray4::new(8));
    Text::new("Gradient 0→15", Point::new(10, 155), mid)
        .draw(display)
        .unwrap();
    Text::new("Checkerboard", Point::new(490, 155), mid)
        .draw(display)
        .unwrap();
    Text::new("16 solid bands", Point::new(10, 295), mid)
        .draw(display)
        .unwrap();
    Text::new("Chebyshev rings", Point::new(490, 295), mid)
        .draw(display)
        .unwrap();

    // Divider lines
    Line::new(Point::new(480, 135), Point::new(480, 404))
        .into_styled(PrimitiveStyle::with_stroke(Gray4::new(8), 1))
        .draw(display)
        .unwrap();
    Line::new(Point::new(0, 270), Point::new(960, 270))
        .into_styled(PrimitiveStyle::with_stroke(Gray4::new(8), 1))
        .draw(display)
        .unwrap();

    // Caption below image
    Text::with_alignment(
        "4-bit pixel data generated at compile time by build.rs, rendered via embedded-graphics ImageRaw",
        Point::new(480, 425),
        label,
        Alignment::Center,
    )
    .draw(display)
    .unwrap();
}

// ── Screen 5: Animation + timing measurement ──────────────────────────────────

fn run_animation(display: &mut Display, button: &Input, delay: &Delay) -> (u64, u64, u64) {
    let large = MonoTextStyle::new(&FONT_10X20, Gray4::BLACK);
    let small = MonoTextStyle::new(&FONT_7X13, Gray4::BLACK);

    // ── Step A: full-screen flush benchmark ──────────────────────────────────
    // fill() marks all 540 rows dirty → flush sends every row
    display.fill(0x0F).unwrap();

    Text::with_alignment(
        "Animation & Partial Refresh",
        Point::new(480, 40),
        large,
        Alignment::Center,
    )
    .draw(display)
    .unwrap();
    Text::with_alignment(
        "The ball moves in a 120-row band. Only those rows are flushed each frame.",
        Point::new(480, 70),
        small,
        Alignment::Center,
    )
    .draw(display)
    .unwrap();
    Text::new(
        "Measuring full-screen flush (all 540 rows)...",
        Point::new(40, 100),
        small,
    )
    .draw(display)
    .unwrap();

    println!("Measuring full flush...");
    let t0 = Instant::now();
    display.flush(DrawMode::BlackOnWhite).unwrap();
    let full_flush_ms = t0.elapsed().as_millis();
    println!("Full flush: {}ms", full_flush_ms);

    // ── Step B: measure hardware clear time ───────────────────────────────────
    println!("Measuring hardware clear...");
    let t0 = Instant::now();
    display.clear().unwrap();
    let clear_ms = t0.elapsed().as_millis();
    println!("Hardware clear: {}ms", clear_ms);

    // Draw the static frame (border + labels) after the clear
    Rectangle::new(Point::new(16, 16), Size::new(928, 508))
        .into_styled(PrimitiveStyle::with_stroke(Gray4::BLACK, 2))
        .draw(display)
        .unwrap();
    Text::with_alignment(
        "Animation & Partial Refresh",
        Point::new(480, 40),
        large,
        Alignment::Center,
    )
    .draw(display)
    .unwrap();
    Text::with_alignment(
        "Ball moves across screen (8 frames). Only the ~80 rows it touches are flushed.",
        Point::new(480, 70),
        small,
        Alignment::Center,
    )
    .draw(display)
    .unwrap();

    // Flush static content — only the tainted rows (title band) are sent
    display.flush(DrawMode::BlackOnWhite).unwrap();

    // ── Step C: animation loop (8 frames, partial flush) ──────────────────────
    // flush() resets the framebuffer to white after every frame, so there is no
    // need to draw a white rectangle to erase the previous ball position —
    // just draw the new ball and flush. Only the ~80 rows the circle touches
    // are marked tainted, keeping the partial flush fast.
    const BALL_DIAM: u32 = 80;
    const BAND_Y: i32 = 210;
    const BAND_H: i32 = 120;
    const FRAMES: u32 = 8;
    const START_X: i32 = 60;
    const STEP_X: i32 = 105;

    let mut sum_partial_ms: u64 = 0;

    for frame in 0..FRAMES {
        let ball_x = START_X + frame as i32 * STEP_X;
        let ball_y = BAND_Y + (BAND_H - BALL_DIAM as i32) / 2;

        // Draw ball — framebuffer is already white after the previous flush()
        Circle::new(Point::new(ball_x, ball_y), BALL_DIAM)
            .into_styled(PrimitiveStyle::with_fill(Gray4::BLACK))
            .draw(display)
            .unwrap();

        // Frame label inside the band
        let mut lbl = Buf::<16>::new();
        lbl.push_str("Frame ");
        lbl.push_u64(frame as u64 + 1);
        Text::new(lbl.as_str(), Point::new(810, BAND_Y + 55), small)
            .draw(display)
            .unwrap();

        let t0 = Instant::now();
        display.flush(DrawMode::BlackOnWhite).unwrap();
        let frame_ms = t0.elapsed().as_millis();
        sum_partial_ms += frame_ms;
        println!("frame {}: {}ms (partial)", frame + 1, frame_ms);
    }

    let partial_avg_ms = sum_partial_ms / FRAMES as u64;

    // Draw timing results at the bottom of the animation screen
    {
        let mut line1 = Buf::<64>::new();
        line1.push_str("Full flush (540 rows): ");
        line1.push_u64(full_flush_ms);
        line1.push_str("ms   |   Partial (~80 rows): ");
        line1.push_u64(partial_avg_ms);
        line1.push_str("ms avg");
        Text::with_alignment(
            line1.as_str(),
            Point::new(480, 390),
            small,
            Alignment::Center,
        )
        .draw(display)
        .unwrap();
    }
    {
        let speedup_x10 = if partial_avg_ms > 0 {
            full_flush_ms * 10 / partial_avg_ms
        } else {
            0
        };
        let mut line2 = Buf::<64>::new();
        line2.push_str("Speedup: ");
        line2.push_u64(speedup_x10 / 10);
        line2.push_str(".");
        line2.push_u64(speedup_x10 % 10);
        line2.push_str("x faster  |  ~80/540 = ~15% of rows updated");
        Text::with_alignment(
            line2.as_str(),
            Point::new(480, 420),
            small,
            Alignment::Center,
        )
        .draw(display)
        .unwrap();
    }
    Text::with_alignment(
        "Note: ghosting is expected — the waveform does not actively drive pixels to white.",
        Point::new(480, 450),
        MonoTextStyle::new(&FONT_6X9, Gray4::BLACK),
        Alignment::Center,
    )
    .draw(display)
    .unwrap();

    display.flush(DrawMode::BlackOnWhite).unwrap();

    wait_for_button(button, delay);

    (clear_ms, full_flush_ms, partial_avg_ms)
}

// ── Screen 6: Timing summary ──────────────────────────────────────────────────

fn draw_timing(display: &mut Display, clear_ms: u64, full_ms: u64, partial_ms: u64) {
    let heading = MonoTextStyle::new(&FONT_10X20, Gray4::BLACK);
    let body = MonoTextStyle::new(&FONT_9X18, Gray4::BLACK);
    let note = MonoTextStyle::new(&FONT_7X13, Gray4::BLACK);

    Rectangle::new(Point::new(16, 16), Size::new(928, 508))
        .into_styled(PrimitiveStyle::with_stroke(Gray4::BLACK, 2))
        .draw(display)
        .unwrap();

    Text::with_alignment(
        "Refresh Timing Summary",
        Point::new(480, 60),
        heading,
        Alignment::Center,
    )
    .draw(display)
    .unwrap();

    Line::new(Point::new(40, 78), Point::new(920, 78))
        .into_styled(PrimitiveStyle::with_stroke(Gray4::BLACK, 1))
        .draw(display)
        .unwrap();

    let rows: [(&str, u64, &str); 3] = [
        (
            "Hardware clear (540 rows):",
            clear_ms,
            "ms   — drives all pixels black then white x4",
        ),
        (
            "Full flush     (540 rows):",
            full_ms,
            "ms   — 15-frame waveform, all rows sent",
        ),
        (
            "Partial flush  (120 rows):",
            partial_ms,
            "ms   — 15-frame waveform, 22% of rows (avg)",
        ),
    ];

    for (i, (label, val, suffix)) in rows.iter().enumerate() {
        let y = 130 + i as i32 * 80;
        Text::new(label, Point::new(60, y), note)
            .draw(display)
            .unwrap();

        let mut num = Buf::<32>::new();
        num.push_u64(*val);
        num.push_str(" ");
        num.push_str(suffix);
        Text::new(num.as_str(), Point::new(100, y + 28), body)
            .draw(display)
            .unwrap();
    }

    Line::new(Point::new(40, 370), Point::new(920, 370))
        .into_styled(PrimitiveStyle::with_stroke(Gray4::BLACK, 1))
        .draw(display)
        .unwrap();

    // Speedup ratio
    let speedup_x10 = if partial_ms > 0 {
        full_ms * 10 / partial_ms
    } else {
        0
    };
    let mut speed_line = Buf::<64>::new();
    speed_line.push_str("Partial refresh is ");
    speed_line.push_u64(speedup_x10 / 10);
    speed_line.push_str(".");
    speed_line.push_u64(speedup_x10 % 10);
    speed_line.push_str("x faster than a full flush.");
    Text::with_alignment(
        speed_line.as_str(),
        Point::new(480, 410),
        heading,
        Alignment::Center,
    )
    .draw(display)
    .unwrap();

    Text::with_alignment(
        "Rows skipped: 420 of 540 per waveform frame (22% updated, 78% skipped via CKV pulse).",
        Point::new(480, 450),
        note,
        Alignment::Center,
    )
    .draw(display)
    .unwrap();

    Text::with_alignment(
        "Press BOOT to restart.",
        Point::new(480, 510),
        note,
        Alignment::Center,
    )
    .draw(display)
    .unwrap();
}

// ── Main ──────────────────────────────────────────────────────────────────────

#[main]
fn main() -> ! {
    esp_println::logger::init_logger_from_env();

    let config = esp_hal::Config::default().with_cpu_clock(esp_hal::clock::CpuClock::_240MHz);
    let peripherals = esp_hal::init(config);

    let psram_config = esp_hal::psram::PsramConfig {
        mode: esp_hal::psram::PsramMode::OctalSpi,
        ..Default::default()
    };
    esp_alloc::psram_allocator!(peripherals.PSRAM, esp_hal::psram, psram_config);

    let button = Input::new(
        peripherals.GPIO0,
        InputConfig::default().with_pull(Pull::Up),
    );

    let mut display = Display::new(
        epaper::pin_config!(peripherals),
        peripherals.DMA_CH0,
        peripherals.LCD_CAM,
        peripherals.RMT,
        peripherals.I2C0,
    )
    .expect("display init");

    let delay = Delay::new();
    delay.delay_millis(100);
    display.power_on();
    delay.delay_millis(10);

    println!("Graphics test — 6 screens. Press BOOT (GPIO0) to advance.");

    // Measure hardware clear time once at start
    println!("Measuring hardware clear...");
    let t0 = Instant::now();
    display.clear().unwrap();
    let initial_clear_ms = t0.elapsed().as_millis();
    println!("Hardware clear: {}ms", initial_clear_ms);

    // ── Screen 0: Title ───────────────────────────────────────────────────────
    draw_title(&mut display);
    println!("Flushing title...");
    display.flush(DrawMode::BlackOnWhite).unwrap();
    wait_for_button(&button, &delay);

    // ── Screen 1: Shapes ──────────────────────────────────────────────────────
    display.clear().unwrap();
    draw_shapes(&mut display);
    println!("Flushing shapes...");
    display.flush(DrawMode::BlackOnWhite).unwrap();
    wait_for_button(&button, &delay);

    // ── Screen 2: Typography ──────────────────────────────────────────────────
    display.clear().unwrap();
    draw_typography(&mut display);
    println!("Flushing typography...");
    display.flush(DrawMode::BlackOnWhite).unwrap();
    wait_for_button(&button, &delay);

    // ── Screen 3: Grayscale ───────────────────────────────────────────────────
    display.clear().unwrap();
    draw_grayscale(&mut display);
    println!("Flushing grayscale...");
    display.flush(DrawMode::BlackOnWhite).unwrap();
    wait_for_button(&button, &delay);

    // ── Screen 4: Image ───────────────────────────────────────────────────────
    display.clear().unwrap();
    draw_image(&mut display);
    println!("Flushing image...");
    display.flush(DrawMode::BlackOnWhite).unwrap();
    wait_for_button(&button, &delay);

    // ── Screen 5: Animation (also measures full + partial flush time) ─────────
    display.clear().unwrap();
    let (clear_ms, full_flush_ms, partial_avg_ms) = run_animation(&mut display, &button, &delay);

    // ── Screen 6: Timing summary ──────────────────────────────────────────────
    display.clear().unwrap();
    draw_timing(&mut display, clear_ms, full_flush_ms, partial_avg_ms);
    println!("Flushing timing summary...");
    display.flush(DrawMode::BlackOnWhite).unwrap();
    println!(
        "Done. clear={}ms full={}ms partial={}ms",
        clear_ms, full_flush_ms, partial_avg_ms
    );
    wait_for_button(&button, &delay);

    loop {}
}
